name: Solution CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Change to working directory
        run: cd dev_application

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake make g++

      - name: Configure CMake
        run: cmake -B dev_application/build -S dev_application

      - name: Build the code
        run: |
          cd dev_application/build
          make

      - name: Run tests
        run: |
          cd dev_application/build
          make test || ./test/assignment_test